# Generated by Django 4.0.3 on 2022-04-04 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp1', '0004_customer_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='type',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='client',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='item',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
