# Generated by Django 4.0.3 on 2022-04-04 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp1', '0005_remove_item_type_remove_orderitem_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='settings',
            field=models.CharField(blank=True, default='', max_length=1000000, null=True),
        ),
    ]
